<?
	$js = $this->helper('js');
?>

<h1>Editace</h1>

<?= $form->getErrorsList() ?>

<?= $form->start() ?>
<table>
<tr>
	<td><?= $form['group_id']->label('Skupina') ?></td>
	<td><?= $form['group_id']->element() ?></td>
</tr>
<tr>
	<td><?= $form['author']->label('Autor') ?></td>
	<td><?= $form['author']->element() ?></td></tr><tr>
	<td><?= $form['text']->label('Text') ?></td>
	<td><?= $form['text']->element() ?></td>
</tr>
<tr>
	<td><?= $form['date']->label('Datum') ?></td>
	<td><?= $form['date']->element() ?></td>
</tr>
<tr>
	<td></td>
	<td><?= $form['submit']->element('Upravit') ?></td>
</tr>
</table>


<?= $form->end() ?>