<style type="text/css">
#hfToolbar {
	position: fixed;
	right: 5px;
	bottom: 5px;
}

#hfContainer {
	position: relative;
	color: #eee;
	background: #222;
	border-collapse: collapse;
	border: 1px solid black;
	font: normal normal 11px/1.4 Consolas, 'Lucida Console', 'Monaco CE', fixed, monospace;
	margin: 0;
	padding: 0;
	opacity: .20;
	width: 300px;
	text-align: left;
}

#hfContainer:hover {
	opacity: 1;
}

#hfContainer th, #hfContainer td {
	padding: 1px 2px;
}

#hfContainer tr:hover td {
	background: #555;
}

#hfContainer th {
	background: #fff;
	color: #000;
}

#hfToolbar abbr {
	border: none;
	letter-spacing: inherit;
	text-transform: inherit;
	font-size: inherit;
}
</style>


<div id="hfToolbar" ondblclick="this.style.display='none';">
<table id="hfContainer">
<?

ksort(self::$toolbar);
foreach (self::$toolbar as $group => $message) {

	if (!empty($group))
		echo '<tr><th>' . strtoupper($group) . ':</th></tr>';

	foreach ($message as $m)
		echo "<tr><td>$m</td></tr>";
}

?>
</table>
</div>