<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://hf.programujte.com
 * @version     0.6 alfa
 * @package     HF
 */

?>
<?php $this->title = 'Nenalezena metoda | Háefko - php5 framework' ?>
<div style="border: 1px solid transparent;">
<div id="err_message" style="background:white;border:1px solid #aaa;margin:100px auto;padding:20px;width:75%;">

<h1 style="color: #a00227;font-size: 20px;margin: 0 0 10px 0;">CHYBA: Nenalezena metoda</h1>
<p style="margin: 15px 0;">Zkontrolujte URL a routing, zda-li jste neudělali překlep.</p>
<p style="margin: 15px 0;">Pro vytvoření metody využijte následující kostru:</p>

<pre>
public function <?= $message ?>()
{
	// váš kód
}
</pre>
<p style="margin: 15px 0;">Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>

</div>
</div>