<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?= $html->encoding() ?>
	<?= $html->title() ?>
	<?= $js ?>
	<style type="text/css" media="screen">
		a {
			color: #1c1a8f;
		}
		table.list {
			border: 1px solid black;
			border-collapse: collapse;
		}
		table.list td {
			border: 1px solid black;
			padding: 3px;
		}
	</style>
</head>
<body style="font-family: sans-serif;">
<?= $content ?>
<br />
<br />
<br />
<br />
Powered by <a href="http://haefko.programujte.com">Háefko</a>.
</body>
</html>