<table class="datagrid">
<thead>
	<tr>
		<?php foreach ($columns as $column): ?>
		<th>
			<?= $html->link($grid->columnUrl($column), $grid->columnLabel($column), $grid->columnStateClass($column)) ?>
			<?= $grid->columnStateNum($column) ?>
		</th>
		<?php endforeach; ?>
		
		<th>Actions</th>
	</tr>
</thead>

<tbody>
	<?php foreach ($rows as $i => $row): ?>
	<tr<?php echo ($i % 2) ? ' class="odd"' : '' ?>>
	<?php foreach ($row as $field): ?>
	<td><?= $field ?></td>
	<?php endforeach; ?>
	<td>
		<?= $html->link($grid->url('update', $row['id']), 'Edit') ?>
		<?= $html->button($grid->url('delete'), $row['id'], 'Delete', 'Do you want delete this entry?') ?>
	</td>
	</tr>
	<?php endforeach; ?>
</tbody>
</table>