<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8.5 - $Id$
 * @package     Haefko_Libs
 */
 
?>
<table class="datagrid">
<thead>
	<tr>
		<?php foreach ($grid->columns as $column): ?>
		<th>
			<?php if (in_array($column, $grid->orderable) || empty($grid->orderable)): ?>
				<?= $html->link($grid->columnUrl($column), $grid->columnLabel($column) . $grid->columnStateNum($column), $grid->columnStateClass($column), false) ?>
			<?php else: ?>
				<?= $grid->columnLabel($column) ?>
			<?php endif; ?>
		</th>
		<?php endforeach; ?>
		<?php if ($grid->showActions): ?>
		<th>Actions</th>
		<?php endif; ?>
	</tr>
</thead>
<tbody>
	<?php foreach ($rows as $i => $row): ?>
	<tr<?php echo ($i % 2) ? ' class="odd"' : '' ?>>
	<?php foreach ($row as $field): ?>
	<td><?= $field ?></td>
	<?php endforeach; ?>
	<?php if ($grid->showActions): ?>
	<td><?= $grid->invokeActionsCallback($this, $row) ?></td>
	<?php endif; ?>
	</tr>
	<?php endforeach; ?>
</tbody>
<tfoot>
	<tr>
	<td colspan="<?= count($grid->columns) + ($grid->showActions ? 1 : 0) ?>">
		<div class="pagination">
		<?php
			$paginator = $grid->query->paginator;

			if (!$paginator->isFirst()) {
				echo $paginator->link('', 1, '<span class="first">First</span>');
				echo $paginator->link('', $paginator->page - 1, '<span class="prev">Previous</span>');
			} else {
				echo '<span class="first-off">First</span>';
				echo '<span class="prev-off">Previous</span>';
			}

			echo '<form>';
			if ($grid->getVar('order') != null)
				echo '<input type="hidden" name="' . $grid->name . '-order" value="' . $grid->getVar('order') . '" />';

			$page = $grid->getVar('page');
			$page = empty($page) ? 1 : $page;
			echo 'Page <input type="text" name="' . $grid->name . '-page" value="' . $page . '" class="text" /> of ' . $paginator->pages;
			echo '</form>';

			if (!$paginator->isLast()) {
				echo $paginator->link('', $paginator->page + 1, '<span class="next">Next</span>');
				echo $paginator->link('', $paginator->pages, '<span class="last">Last</span>');
			} else {
				echo '<span class="next-off">Next</span>';
				echo '<span class="last-off">Last</span>';
			}
		?>
		</div>
	</td>
	</tr>
</tfoot>
</table>