<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8.5 - $Id$
 * @package     Haefko_Libs
 */
 
?>
<table class="datagrid">
<thead>
	<tr>
		<?php foreach ($grid->columns as $column): ?>
		<th>
			<?php if (in_array($column, $grid->orderable) || empty($grid->orderable)): ?>
				<?= $html->link($grid->columnUrl($column), $grid->columnLabel($column) . $grid->columnStateNum($column), $grid->columnStateClass($column), false) ?>
			<?php else: ?>
				<?= $grid->columnLabel($column) ?>
			<?php endif; ?>
		</th>
		<?php endforeach; ?>
		<?php if ($grid->showActions): ?>
		<th>Actions</th>
		<?php endif; ?>
	</tr>
</thead>
<tbody>
	<?php foreach ($rows as $i => $row): ?>
	<tr<?php echo ($i % 2) ? ' class="odd"' : '' ?>>
	<?php foreach ($row as $field): ?>
	<td><?= $field ?></td>
	<?php endforeach; ?>
	<?php if ($grid->showActions): ?>
	<td>
		<?= $html->link($grid->url('update', $row['id']), '<span>Edit</span>', array('class' => 'edit'), false) ?>
		<?= $html->link($grid->url('delete', $row['id']), '<span>Delete</span>', array('class' => 'delete'), false) ?>
	</td>
	<?php endif; ?>
	</tr>
	<?php endforeach; ?>
</tbody>
</table>

<?= $grid->query->paginator->render('') ?>