<h1>Seznam skupin</h1>
<hr />

<ol>
<? Router::$args['id'] = 'AAA'; ?>
<? Router::$args['group'] = 'BBB'; ?>
<?php foreach ($groups as $group) { ?>
	<li><?= $this->link("/messages/group:$group[group_id]", $group['name']) ?></li>
<?php } ?>
</ol>

<br />
<br />
<br />
<br />
<a href="/hlen-demo-app.zip">Demo</a><br />
<br />
<a href="http://hlen.programujte.com">Officialni stranky</a>

