{**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 *}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<title>{block #title}{if isset($title)}{$title}{else}Haefko default layout{/if}{/block}</title>
	{block #header}{/block}
</head>
<body>
	{if Config::read('core.debug') > 0}
	<h2>This is default Haefko framework layout.</h2>
	<p>Please switch to your own layout.</p>
	<hr />
	{/if}
	{block #content}{/block}
</body>
</html>