{**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 *}
{mimetype 'application/rss+xml'}
{php echo '<' . '?xml version="1.0" encoding="utf-8"?>' . "\n"}
<rss version="2.0">
<channel>
	<generator>haefko framework - http://haefko.skrasek.com</generator>
	<docs>http://blogs.law.harvard.edu/tech/rss</docs>

	<title>{$title}</title>
	<description>{$description}</description>
	<lastBuildDate>{$rss->date()}</lastBuildDate>
	{if isset($link)}<link>{$link}</link>{/if}
	{if isset($image['title']) && isset($image['src']) && isset($image['link'])}
	<image>
		<title>{$image['title']}</title>
		<url>{$image['scr']}</url>
		<link>{link $this->image['link'], null, true}</link>
	</image>
	{/if}

	{block #content}{/block}
</channel>
</rss>