multi:
    localhost:
        Core.debug: 2
        Db.connection:
            driver: mysqli
            host: localhost
            username: root
            database: konference
            charset: utf8
            lazy: true