{**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 *}
{block prepend #title}Internal server error {/block}
{block #content}
<div class="error">
	<h1>Internal server error</h1>
	<p>We are apologizing. The requested service is not currently available.</p>
	<p>The server encountered an internal error.</p>
	<ul>
		<li>Wait a moment and then repeat the action please.</li>
		<li>If the error doesn't disappear, contact administrator / author please.</li>
	</ul>
</div>
{/block}