<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8.5 - $Id$
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php
	$this->title = 'Missing view | haefko';
?>
<div class="error">
	<h1>ERROR: Missing view</h1>
	<p>Check whether you created view file <code><?= $variable ?></code>.</p>
</div>