<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php
	$this->title = 'Missing file | haefko';
?>
<div class="error">
	<h1>ERROR: Missing file</h1>
	<p>Check whether you created missing file <code><?= $variable ?></code>.</p>
</div>