<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 */


?>
{block prepend #title}Missing controller class | haefko {/block}
{block #content}
<div class="error">
	<h1>ERROR: Missing controller class</h1>
	<p>Create missing controller <code>{$variable}</code>. Use this basic skeleton:</p>
<pre><code class="php">class {$variable} extends AppController
{
	public function {$application->router->action}Action()
	{
		// your code
	}
}</code></pre>
</div>
{/block}