<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 */


?>
{block prepend #title}Missing file | haefko {/block}
{block #content}
<div class="error">
	<h1>ERROR: Missing file</h1>
	<p>Check whether you created missing file <code>{$variable}</code>.</p>
</div>
{/block}