{**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.9 - $Id$
 * @package     Haefko
 * @subpackage  Templates
 *}
{block prepend #title}No routing match | haefko {/block}
{block #content}
<div class="error">
	<h1>ERROR: No routing match</h1>
	<p>Check URL and routing for keying mistakes.</p>
	<p>Basic routing suggestion: </p>
<pre><code class="php">$router = $application-&gt;getRouter();
$router-&gt;defaults(array('controller' =&gt; 'default'));
$router-&gt;connect('/');
$router-&gt;connect('/&lt;:controller&gt;');
$router-&gt;connect('/&lt;:controller&gt;/&lt;:action&gt;', null, true);
</code></pre>
</div>
{/block}