<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php $this->title = 'Nenalezen view | Háefko - your php5 framework' ?>
<div class="error">
    <h1>CHYBA: Nenalezen soubor view</h1>
    <p>Zkontrolujte, zda-li jste vytvořili soubor view: <em><?= $message ?></em>.</p>
    <p><strong>Poznámka:</strong> Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>
</div>