<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php $this->title = 'Neproběhl routing | Háefko - your php5 framework' ?>
<div class="error">
    <h1>CHYBA: Nebyl proveden routing</h1>
    <p>Zkontrolujte URL a routing, zda-li jste neudělali překlep.</p>
    <p>Pokud ne, zřejmě jste zatím nevytvořili správné routování.</p>
    <p><strong>Poznámka:</strong> Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>
</div>