<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://hf.programujte.com
 * @version     0.6 alfa
 * @package     HF
 */

?>
<?php $this->title = 'Neproběhl routing | Háefko - your php5 framework' ?>
<div class="error">
    <h1>CHYBA: Nebyl proveden routing</h1>
    <p>Zkontrolujte URL a routing, zda-li jste neudělali překlep.</p>
    <p>Pokud ne, zřejmě jste zatím nevytvořili správné routování.</p>
    <p>Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>
</div>