<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php
	$this->title = 'No routing | haefko';
?>

<div class="error">
	<h1>ERROR: No routing</h1>
	<p>Check URL and routing for keying mistakes.</p>
</div>