<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2007 - 2009, Jan Skrasek
 * @link        http://haefko.skrasek.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8.5 - $Id$
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php
	$this->title = 'No routing match | haefko';
?>

<div class="error">
	<h1>ERROR: No routing match</h1>
	<p>Check URL and routing for keying mistakes.</p>
	<p>Basic routing suggestion: </p>
<pre><code class="php">$router = $application-&gt;getRouter();
$router-&gt;defaults(array('controller' =&gt; 'default'));
$router-&gt;connect('/');
$router-&gt;connect('/&lt;:controller&gt;');
$router-&gt;connect('/&lt;:controller&gt;/&lt;:action&gt;', null, true);
</code></pre>
</div>