<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://hf.programujte.com
 * @version     0.6 alfa
 * @package     HF
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex,noarchive" />
    <meta name="generator" content="HF - php5 framework" />
    <title>HF: Neodchycená výjimka</title>
    <style type="text/css" media="screen">
    body {
        background: #f8f4ed;
        font-family: sans-serif;
        padding: 0;
        margin: 0;
    } 
    a {
        color: #079fd8;
        text-decoration: none
    } 
    a:hover {
        text-decoration: underline;
    } 
    h1 {
        background: #f2fafe;
        border-bottom: 3px solid #d5effb;
        font-size: 22px;
        margin: 0;
        padding: 5px 20px;
    }
    h2 {
        font-size: 18px;
        margin: 0;
    }
    code{
        background: white;
        border: 1px solid #dfd5c3;
        padding: 2px 3px;
    }    
    pre {
        background: white;
        border: 1px solid #dfd5c3;
        padding: 2px 3px;
        font-size: 12px;
        margin: 0;
    }
    </style>
</head>
<body>
<h1>HF: Neodchycená výjimka</h1>
<div style="padding: 10px 20px;">
    <h3 style="color: #75011b;"><?= $exception->getMessage(); ?></h3>
    řádek <code><?= $exception->getLine(); ?></code> - <code><?= $exception->getFile(); ?></code>

    <br /><br />
    <pre style="text-align: left;"><?= $trace ?>
    </pre>

    <p>
        Vygenerováno v <?php echo date('h:i - d.m.Y') ?><br />
        <a href="http://hf.programujte.com">HF powered</a> - version <?= Application::$frameworkVersion ?><br />
    </p>
</div>
</body>
</html>