<?php


/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @version     0.7
 * @package     Haefko
 */


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex,noarchive" />
    <meta name="generator" content="Háefko - your php5 framework" />
    <title>Exception: <?= htmlspecialchars($exception->getMessage()) ?></title>
    <style type="text/css" media="screen">
    body {
        font-family: Calibri, sans-serif;
        padding: 0;
        margin: 0;
    }

    a {
        color: #079fd8;
        text-decoration: none
    }

    a:hover {
        text-decoration: underline;
    }

    h1 {
        background: #6F071E;
        color: white;
        font-size: 28px;
        margin: 0;
        padding: 15px 20px;
    }

    code {
        display: block;
        font-family: Consolas, 'Lucida Console', 'Monaco CE', fixed, monospace;
        background: #EFF9FF;
        border: 1px solid #86CAEF;
        padding: 2px;
        width: 850px;
        overflow: auto;
    }

    span.line {
        background: red;
        position: absolute;
        width: 850px;
        height: 20px;
        opacity: 0.2;
        filter: alpha(opacity=20);
        -khtml-opacity: 0.2;
    }
    </style>
</head>
<body>
<h1><?= $exception->getMessage(); ?></h1>
<?php
$i = 0;
$trace = $exception->getTrace();


foreach ($trace as $k => $item) {
    if (!preg_match('#dibi|haefko#i', $item['file'])) {
        $i = $k;
        break;
    }
}

$l = $trace[$i]['line'] - 1;
$file = highlight_file($trace[$i]['file'], true);
$file = preg_split('#<br />#', $file);
$file[$l] = '<span class="line"></span>' . $file[$l];
$file = implode('<br />', $file);
?>

<div style="padding: 10px 20px;">
    <br />
    <p><?= $trace[$i]['file'] ?> (<?= $l ?>):</p>
    <?= $file ?>

    <p>
        Čas generování: <?= self::getTime() ?>ms<br />
        Server: <?= htmlspecialchars($_SERVER['SERVER_SOFTWARE']) ?><br />
        Vygenerováno: <?php echo date('d.m.Y, h.i') ?><br />
        Powered by: <a href="http://haefko.programujte.com">Háefko</a>, <?= Application::$version ?><br />
    </p>
</div>
</body>
</html>