<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @version     0.7
 * @package     Haefko
 */

?>
<style type="text/css" media="screen">
#hf-debug-ribbon {
    opacity: 0.3;
    filter: alpha(opacity=30);
    -moz-opacity: 0.3;
    -khtml-opacity: 0.3;
    background: #222;
    color: #ddd;
    position: fixed;
    top: 0;
    left: 0;
    text-align: left;
    width: 18px;
    height: 18px;
    overflow: hidden;
}

#hf-debug-ribbon:hover {
    opacity: 1;
    filter: alpha(opacity=100);
    -moz-opacity: 1;
    -khtml-opacity: 1;
    width: auto;
    height: auto;
}

#hf-debug-ribbon a {
    color: white;
}

#hf-debug-ribbon ul {
    padding-left: 15px;
    margin: 0;
    font-size: 12px;
}

#hf-debug-ribbon-config, #hf-debug-ribbon-sql {
    border: 1px solid #444;
    border-collapse: collapse;
    background: #333;
    margin-top: 2px;
    padding: 2px;
}

#hf-debug-ribbon-sql td, #hf-debug-ribbon-sql th {
    border: 1px solid #666;
    padding: 0 3px;
}

#hf-debug-ribbon-sql td {
    background: #444;
}

</style>
<script type="text/javascript">
//<![CDATA[
function hfRibbonToogler(id, id2) {
    div = document.getElementById(id2);
    div.style.display = 'none';
    div = document.getElementById(id);
    div.style.display = (div.style.display == '') ? 'none' : '';
}
//]]>
</script>
<div id="hf-debug-ribbon">
    <div id="hf-debug-ribbon-toolbar">
        HF <span style="font-size: 12px">v.<?= Application::$version ?></span> ::
        <?= Debug::getTime() ?> ms ::
        <a href="javascript:hfRibbonToogler('hf-debug-ribbon-config', 'hf-debug-ribbon-sql')">config</a>&nbsp;
        <?php if (!is_null($sql)) { ?> :: <a href="javascript:hfRibbonToogler('hf-debug-ribbon-sql', 'hf-debug-ribbon-config')">sql</a><?php } ?>&nbsp;&nbsp;
    </div>

    <?php if (!is_null($sql)) { ?>
    <table style="display: none" id="hf-debug-ribbon-sql">
        <tr><th>SQL</th><th>time</th><th>rows</th></tr>
        <?php foreach ($sql as $row) { ?>
        <tr><td><?= $row['sql'] ?></td><td><?= sprintf('%0.3f', $row['time'] * 1000) ?> ms</td><td><?= $row['rows'] ?></td></tr>
        <?php } ?>
    </table>
    <?php } ?>

    <div id="hf-debug-ribbon-config" style="display: none;">
        <?= self::readableArray(Config::getConfig()) ?>
    </div>
</div>