<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @version     0.7
 * @package     Haefko
 */

?>
<style type="text/css" media="screen">
#hf-debug-ribbon {
    opacity: 0.2;
    filter: alpha(opacity=20);
    -moz-opacity: 0.2;
    -khtml-opacity: 0.2;
    background: #f8f4ed;
    border: 1px solid #8f826b;
    padding: 2px 3px;
    position: fixed;
    top: 0;
    left: 0;
    text-align: left;
}

#hf-debug-ribbon:hover {
    opacity: 1;
    filter: alpha(opacity=100);
    -moz-opacity: 1;
    -khtml-opacity: 1;
}

#hf-debug-ribbon-sql {
    border-collapse: collapse;
    border: 1px solid #dfd5c3;
    background: white;
    margin-top: 4px;
    font-size: 11px;
    width: auto;
}

#hf-debug-ribbon-sql td {
    border: 1px solid #dfd5c3;
    padding: 1px 2px;
}

#hf-debug-ribbon-sql th {
    border: 1px solid #dfd5c3;
    background: #dfd5c3;
    padding: 1px 2px;
}

#hf-debug-ribbon ul {
    border: 1px solid #dfd5c3;
    background: white;
    list-style-type: none;
    font-size: 11px;
    padding: 1px 3px;
    margin: 4px 0 0 0;
}

#hf-debug-ribbon ul ul {
    border: none;
    padding-left: 20px;
    margin: 0;
    list-style-type: circle;
}

</style>
<script type="text/javascript">
//<![CDATA[
function hf_ribbon_toogler(id) {
    div = document.getElementById(id);
    div.style.display = (div.style.display == '') ? 'none' : '';
}
//]]>
</script>
<div id="hf-debug-ribbon">
    <div id="hf-debug-ribbon-toolbar">
        Háefko <span style="font-size: 12px">(<?= Application::$version ?>)</span> |
        <?= $time ?> ms |
        <a href="javascript:hf_ribbon_toogler('hf-debug-ribbon-config')">config</a>
        <?php if (!is_null($sql)) { ?> | <a href="javascript:hf_ribbon_toogler('hf-debug-ribbon-sql')">sql</a><?php } ?>
    </div>

    <?php if (!is_null($sql)) { ?>
    <table style="display: none" id="hf-debug-ribbon-sql">
        <tr><th>sql</th><th>time</th><th>rows</th></tr>
        <?php foreach ($sql as $row) { ?>
        <tr><td><?= $row['sql'] ?></td><td><?= sprintf('%0.3f', $row['time'] * 1000) ?> ms</td><td><?= $row['rows'] ?></td></tr>
        <?php } ?>
    </table>
    <?php } ?>

    <div style="display: none;" id="hf-debug-ribbon-config">
        <?= Debug::readableArray(Config::getConfig()) ?>
    </div>
</div>