<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


$this->title = 'Stránka nebyla nenalezena';
Http::headerError(404);

?>
<div class="error">
	<h1>Stránka neexistuje</h1>
	<p>Omlouváme se Vám, ale Vámi požadovaná stránka nebyla na serveru nelazena.</p>
	<p>Při Vašem požadavku mohly nastat následující problémy:
		<ul>
			<li>Stránka na serveru neexistuje</li>
			<li>Stránka byla na server přesunuta nebo zrušena</li>
			<li>Nenabízíme vámi požadovanou službu</li>
		</ul>
	</p>
	<p>Pro novou navigaci pokračujte na <?= $html->link('', 'úvodní stránku') ?>.</p>
	<p>Pokud jste přesvědčeni, že zobrazení této chyby je nedopatření, kontaktujte, prosím, autora.</p>
</div>