<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php $this->title = 'Interní chyba serveru' ?>
<div class="error">
    <h1>Nastala interní chyba serveru</h1>
    <p>Omlouváme se Vám, ale Vámi požadovaná stránka není k dispozici.</p>
    <p>Při Vašem požadavku nastala na serveru interní chyba.
        <ul>
            <li>Chvíli počkejte a pak zkuste akci zopakovat.</li>
            <li>Pokud chyba přetrvává, kontaktujte prosím autora.</li>
        </ul>
    </p>
    <p>Pokud jste přesvědčeni, že zobrazení této chyby je nedopatření, kontaktujte, prosím, autora.</p>
</div>