<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://haefko.programujte.com
 * @license     http://www.opensource.org/licenses/mit-license.html
 * @version     0.8
 * @package     Haefko_Application
 * @subpackage  View
 */


?>
<?php $this->title = 'Nenalezena metoda | Háefko - your php5 framework' ?>
<div class="error">
    <h1>CHYBA: Nenalezena metoda</h1>
    <p>Zkontrolujte URL a routing, zda-li jste neudělali překlep.</p>
    <p>Pro vytvoření metody využijte následující kostru:
        <pre>
        public function <?= $message ?>()
        {
            // váš kód
        }
        </pre>
    </p>
    <p><strong>Poznámka:</strong> Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>
</div>