<?php

/**
 * Haefko - your php5 framework
 *
 * @author      Jan Skrasek <skrasek.jan@gmail.com>
 * @copyright   Copyright (c) 2008, Jan Skrasek
 * @link        http://hf.programujte.com
 * @version     0.6 alfa
 * @package     HF
 */

?>
<?php $this->title = 'Nenalezen view | Háefko - your php5 framework' ?>
<div class="error">
    <h1>CHYBA: Nenalezen soubor view</h1>
    <p>Zkontrolujte, zda-li jste vytvořili soubor view: <em><?= $message ?></em>.</p>
    <p>Po vypnutí ladícího režimu bude tato chyba nahrazena E404.</p>
</div>